services:
  - type: web
    name: ecabsd-web
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    numInstances: 1
    envVars:
      - key: PORT
        value: 8000
      - key: IS_RENDER
        value: "true"
      - key: RENDER
        value: "true"
